<?php
// Define all URL slug variables
$react_native = "react-native-app-development-company";
$home = "index";
$ios = "ios-app-developement-company";
$flutter = "flutter-application-development-company";
$android = "android-application-development";
$healthcare = "healthcare";
$hire_reactJs = "hire-react-js-developer";
$hire_php = "hire-php-developer";
$reactjs = "react-js-app-development-company";
$angular = "angular-development-company";
$telemedicine = "telemedicine";
$telehealth = "telehealth";
$hybrid = "hybrid-app-development-company";
$rpm = "remote-patient-monitoring-software-development";
$about = "about-us";
$contact = "contact";
$industries = "industries";
$laravel = "laravel-development";
$node = "node-js-development";
$hms = "hospital-management";
$emr = "ehr-emr-phr";
$realestate = "real-estate";
$fintech = "finance-app-development-company";
$travel = "travel-app-development-services";
$logistic = "logistic-software-development-company";
$wordpress = "wordpress-development-company";
$crossplatform = "cross-platform-application-development";
$mobilegame = "mobile-game-development-company";
$fooddelivery = "food-delivery-app-development-company";
$e_comerce = "ecommerce-app-development-services";
$socialMedia = "social-media-app-development-company";
$education_app = "education-app-development";
$e_learning = "e-learning";
$saas = "saas-development-company";
$entertainment = "entertainment-app-development-company";
$fashion_beauti = "fashion-and-beauty-application-development-company";
$goverment = "government-app-development-company";
$pos = "pos-development-company";
$pos2 = "pos";
$telemedicine_sa = "telemedicine-app-development-services-in-saudi-arabia";
$telemedicine_riyadh = "telemedicine-app-development-services-in-riyadh";
$rpm_sa = "remote-patient-monitoring-software-development-in-saudi-arabia";
$rpm_riyadh = "remote-patient-monitoring-software-development-in-riyadh";
$healthcare_sa = "healthcare-app-development-company-in-saudi-arabia";
$healthcare_riyadh = "healthcare-app-development-company-in-riyadh";
$hospital_mng_india = "hospital-management-software-development-in-india";
$telemedicine_in = "telemedicine-app-development-company-in-india";
$rpm_india = "remote-patient-monitoring-software-development-in-india";
$healthcare_india = "healthcare-app-development-company-in-india";
$telehealth_india = "telehealth-app-development-company-in-india";
$thankyou = "thankyou";
$err404 = "404";
$analytics_perfomance = "analytics-performance";
$generativeAI = "generative-ai-development-services";
$chatbotSolution = "chatbot-solution";
$aiAgent = "ai-agent-development-services";
$ragSolutions = "rag-solutions";
$aiAutomation = 'ai-automation-workflow-solutions';
$machineLearning = 'machine-learning-development-services';
$nlp = 'nlp-solutions';
$multimodalAI = 'multimodal-ai-development';
$computerVision = "computer-vision-solutions";

// infrastructure management
$infrastructure_management = "infrastructure-management-services";
$cloud_architecture = "cloud-architecture-infrastructure";
$cloud_managed_services = "cloud-managed-services";


$rpm_arizona = "remote-patient-monitoring-software-development-in-arizona";
$rpm_california = "remote-patient-monitoring-software-development-in-california";
$rpm_canada = "remote-patient-monitoring-software-development-in-canada";
$rpm_colorado = "remote-patient-monitoring-software-development-in-colorado";
$rpm_connecticut = "remote-patient-monitoring-software-development-in-connecticut";
$rpm_florida = "remote-patient-monitoring-software-development-in-florida";
$rpm_georgia = "remote-patient-monitoring-software-development-in-georgia";
$rpm_ghana = "remote-patient-monitoring-software-development-in-ghana";
$rpm_illinois = "remote-patient-monitoring-software-development-in-illinois";
$rpm_jordan = "remote-patient-monitoring-software-development-in-jordan";
$rpm_maryland = "remote-patient-monitoring-software-development-in-maryland";
$rpm_massachusetts = "remote-patient-monitoring-software-development-in-massachusetts";
$rpm_mexico = "remote-patient-monitoring-software-development-in-mexico";
$rpm_michigan = "remote-patient-monitoring-software-development-in-michigan";
$rpm_nevada = "remote-patient-monitoring-software-development-in-nevada";
$rpm_jersey = "remote-patient-monitoring-software-development-in-new-jersey";
$rpm_new_york = "remote-patient-monitoring-software-development-in-new-york";
$rpm_nigeria = "remote-patient-monitoring-software-development-in-nigeria";
$rpm_carolina = "remote-patient-monitoring-software-development-in-north-carolina";
$rpm_ohio = "remote-patient-monitoring-software-development-in-ohio";
$rpm_oklahoma = "remote-patient-monitoring-software-development-in-oklahoma";
$rpm_pennsylvania = "remote-patient-monitoring-software-development-in-pennsylvania";
$rpm_tanzania = "remote-patient-monitoring-software-development-in-tanzania";
$rpm_texas = "remote-patient-monitoring-software-development-in-texas";
$rpm_uae = "remote-patient-monitoring-software-development-in-uae";
$rpm_virginia = "remote-patient-monitoring-software-development-in-virginia";
$rpm_washington = "remote-patient-monitoring-software-development-in-washington";
$healthcare_uae = "healthcare-app-development-company-in-uae";
$telemedicine_uae = "telemedicine-app-development-company-in-uae";
$telehealth_uae = "telehealth-app-development-company-in-uae";
$healthcare_qatar = "healthcare-app-development-company-in-qatar";
$emr_uae = "ehr-emr-phr-development-in-uae";
$healthcare_jeddah = "healthcare-app-development-company-in-jeddah";
$portfolio = "portfolio";
$ott_app = "ott-app-development-company";
$mobil_app_dev = "mobile-app-development-company";
$healthcare_jordan = "healthcare-app-development-company-in-jordan";
$healthcare_oman = "healthcare-app-development-company-in-oman";
$ai_service = "ai-software-development-company";
$crm_page = "crm-development-company";
$blockchain = "blockchain-development-company";
$realestatess = "real-estate-software-solutions";
// Use a map instead of many if-else statements
$urlMap = [
   $react_native => "React Native Development",
   $home => "Home Page",
   $ios => "IOS Development",
   $flutter => "Flutter App Development",
   $android => "Android App Development",
   $healthcare => "Healthcare Page",
   $hire_reactJs => "Hire React JS Developer",
   $hire_php => "Hire PHP Developer",
   $hybrid => "Hybrid Development",
   $reactjs => "React JS Development",
   $telehealth => "Telehealth Development",
   $telemedicine => "Telemedicine Development",
   $rpm => "RPM Development",
   $angular => "Angular Development",
   $about => "About Us Page",
   $contact => "Contact Page",
   $industries => "Industries Page",
   $laravel => "Laravel Development",
   $node => "Node JS Development",
   $hms => "Hospital Management System Development",
   $emr => "EHR EMR PHR Development",
   $realestate => "Real Estate Development",
   $fintech => "Finance App Development",
   $travel => "Travel App Development",
   $logistic => "Logistic App Development",
   $wordpress => "WordPress Development",
   $crossplatform => "Cross Platform Development",
   $mobilegame => "Mobile Game Development",
   $fooddelivery => "Food Delivery App Development",
   $e_comerce => "Ecommerce App Development",
   $socialMedia => "Social Media App Development",
   $education_app => "Education App Development",
   $e_learning => "E-Learning App Development",
   $saas => "Saas App Development",
   $entertainment => "Entertainment App Development",
   $fashion_beauti => "Fashion And Beauty App Development",
   $goverment => "Government App Development",
   $pos => "POS App Development",
   $pos2 => "POS",
   $telemedicine_sa => "Telemedicine App Development Saudi Arabia",
   $telemedicine_riyadh => "Telemedicine App Development Riyadh",
   $rpm_sa => "RPM App Development Saudi Arabia",
   $rpm_riyadh => "RPM App Development Riyadh",
   $healthcare_sa => "Healthcare App Development Saudi Arabia",
   $healthcare_riyadh => "Healthcare App Development Riyadh",
   $hospital_mng_india => "Hospital Management Software Development India",
   $telemedicine_in => "Telemedicine App Development India",
   $rpm_india => "RPM App Development India",
   $healthcare_india => "Healthcare App Development India",
   $telehealth_india => "Telehealth App Development India",
   $err404 => "404 Page",
   $analytics_perfomance => "Analytics Performance",
   $rpm_arizona => "RPM App Development Arizona",
   $rpm_california => "RPM App Development California",
   $rpm_canada => "RPM App Development Canada",
   $rpm_colorado => "RPM App Development Colorado",
   $rpm_connecticut => "RPM App Development Connecticut",
   $rpm_florida => "RPM App Development Florida",
   $rpm_georgia => "RPM App Development Georgia",
   $rpm_ghana => "RPM App Development Ghana",
   $rpm_illinois => "RPM App Development Illinois",
   $rpm_jordan => "RPM App Development Jordan",
   $rpm_maryland => "RPM App Development Maryland",
   $rpm_massachusetts => "RPM App Development Massachusetts",
   $rpm_mexico => "RPM App Development Mexico",
   $rpm_michigan => "RPM App Development Michigan",
   $rpm_nevada => "RPM App Development Nevada",
   $rpm_jersey => "RPM App Development New Jersey",
   $rpm_new_york => "RPM App Development New York",
   $rpm_nigeria => "RPM App Development Nigeria",
   $rpm_carolina => "RPM App Development North Carolina",
   $rpm_ohio => "RPM App Development Ohio",
   $rpm_oklahoma => "RPM App Development Oklahoma",
   $rpm_pennsylvania => "RPM App Development Pennsylvania",
   $rpm_tanzania => "RPM App Development Tanzania",
   $rpm_texas => "RPM App Development Texas",
   $rpm_uae => "RPM App Development UAE",
   $rpm_virginia => "RPM App Development Virginia",
   $rpm_washington => "RPM App Development Washington",
   $healthcare_uae => "Healthcare App Development UAE",
   $telemedicine_uae => "Telemedicine App Development UAE",
   $telehealth_uae => "Telehealth App Development UAE",
   $emr_uae => "EHR EMR PHR Development UAE",
   $portfolio => "Portfolio",
   $thankyou => "Thank You",
   $ott_app => "OTT App Development",
   $mobil_app_dev => "Mobile App Development",
   $healthcare_jeddah => "Healthcare App Development Jeddah",
   $healthcare_qatar => "Healthcare App Development Qatar",
   $healthcare_jordan => "Healthcare App Development Jordan",
   $healthcare_oman => "Healthcare App Development Oman",
   $ai_service => "Ai Service Page",
   $crm_page => "CRM App Development",
   $blockchain => "Blockchain App Development",
   $realestatess => "Real Estate Software Solutions",
   $generativeAI => "Generative AI Development Services",
   $chatbotSolution => "Chatbot Solution",
   $aiAgent => "AI Agent Development Services",
   $ragSolutions => "RAG Solutions",
   $aiAutomation => "AI Automation Workflow Solutions",
   $machineLearning => "Machine Learning Development Services",
   $nlp => "NLP Solutions",
   $multimodalAI => "Multimodal AI Development",
   $computerVision => "Computer Vision Solutions",
   $infrastructure_management => "Infrastructure Management Services",
   $cloud_architecture => "Cloud Architecture & Infrastructure Services",
   $cloud_managed_services => "Cloud Managed Services",
];

// Determine page title based on $url
$data = $urlMap[$url] ?? "Page URL not found";
